[project]
name = 'Universal-Energy-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.energy-portal-nft]
path = 'contracts/energy-portal-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-transfer-agreement]
path = 'contracts/energy-transfer-agreement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
